import Header from "@/components/header"

export const metadata = {
  title: 'Saray',
  description: 'Generated by Melih',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <Header/>
      <body>{children}</body>
    </html>
  )
}
